#!/bin/sh

code --install-plugin DougFinke.vscode-pandoc
code --install-plugin EditorConfig.EditorConfig
code --install-plugin HookyQR.beautify
code --install-plugin KTamas.laravel-blade
code --install-plugin MehediDracula.php-namespace-resolver
code --install-plugin Zignd.html-css-class-completion
code --install-plugin akamud.vscode-caniuse
code --install-plugin bajdzis.vscode-database
code --install-plugin ban.spellright
code --install-plugin bmewburn.vscode-intelephense-client
code --install-plugin christian-kohler.npm-intellisense
code --install-plugin codezombiech.gitignore
code --install-plugin codingyu.laravel-goto-view
code --install-plugin daylerees.rainglow
code --install-plugin dbaeumer.vscode-eslint
code --install-plugin dzannotti.vscode-babel-coloring
code --install-plugin eg2.tslint
code --install-plugin eg2.vscode-npm-script
code --install-plugin formulahendry.vscode-mysql
code --install-plugin gerane.Theme-bashling
code --install-plugin jakebathman.mysql-syntax
code --install-plugin jblack.mysql-scratchpad
code --install-plugin kevinkyang.auto-comment-blocks
code --install-plugin liuji-jim.vue
code --install-plugin lonefy.vscode-JS-CSS-HTML-formatter
code --install-plugin mikestead.dotenv
code --install-plugin mrmlnc.vscode-apache
code --install-plugin ms-vscode.sublime-keybindings
code --install-plugin msjsdiag.debugger-for-chrome
code --install-plugin neilbrayfield.php-docblocker
code --install-plugin odubuc.mysql-inline-decorator
code --install-plugin patbenatar.advanced-new-file
code --install-plugin robinbentley.sass-indented
code --install-plugin shanoor.vscode-nginx
code --install-plugin sleistner.vscode-fileutils
code --install-plugin smlombardi.slime
code --install-plugin waderyan.babelrc
code --install-plugin waderyan.gitblame
code --install-plugin yzane.markdown-pdf
code --install-plugin yzhang.markdown-all-in-one