#!/bin/sh
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension calebporzio.simple-php-cs-fixer
code --install-extension christian-kohler.npm-intellisense
code --install-extension cjhowe7.laravel-blade
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.github-vscode-theme
code --install-extension ikappas.phpcs
code --install-extension jcbuisson.vue
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mikestead.dotenv
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension mrmlnc.vscode-postcss-sorting
code --install-extension neilbrayfield.php-docblocker
code --install-extension sdras.night-owl
code --install-extension teabyii.ayu
code --install-extension yzhang.markdown-all-in-one
